### ISSUE TITLE
有关去掉 KV WAL 的 safety 问题

### ISSUE THREAD

**Issue by OneSizeFitsQuorum** [TPC-TiKV/rfc#4]
很不错的项目，提个疑问，欢迎赐教~

> 为了实现这一目标，raft engine 使用 async I/O 也是必需的，kv db 同样需要使用 async I/O，但 kv db 理论上可以不写 WAL，因为数据可通过 raft log 回放且该功能已有方案，在 hackathon 上会强行去掉 kv db 的 WAL。

RocksDB 跨 CF 的原子性正是通过 [WAL](https://github.com/facebook/rocksdb/wiki/Column-Families) 实现的，如果这里去掉的话还怎么保证实现 Percolator 时 CFDefault, CFLock, CFWrite 3 个 CF 之间的原子性呢？

**Comment by youjiali1995** [comment]
https://github.com/facebook/rocksdb/wiki/Atomic-flush

**Comment by OneSizeFitsQuorum** [comment]
这样就有可能避免 WAL 的双写了，加上测试感觉都可以算是一个单独的工作了 hh。感谢回复~
